name: GitHub Actions Demo   # Name not necessary (but helps with identification)
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€  # In this case, github.actor is my GitHub username (because I pushed modified repo to GitHub)
on: # "on:" Defines what event to run the workflow on
    push:
        branches:
        - main
    # pull_request:
    # workflow_dispatch:  # Allows manual triggering of the workflow from the Actions tab in the GitHub repo
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest  # The type of virtual host (runner) to run the job on
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: exit 1
      - name: Check out repository code
        uses: actions/checkout@v4   # Existing action (to check out the repository code)
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - if: always()
      # This ensures the next step runs even if the previous step fails
        run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."

  Second-job:
    needs: Explore-GitHub-Actions # 
    runs-on: ubuntu-latest
    steps:
        - run: echo "This is the second job."

# Help: https://docs.github.com/en/actions/reference/workflows-and-actions
# Existing Actions: https://github.com/marketplace?type=actions